version: "3.8"

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=/api
    ports:
      - "80:80"
    # environment:
    #   - REACT_APP_API_URL=/api
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - "5000:5000"
